require:
  - standard
  - rubocop-rails

inherit_gem:
  standard: config/ruby-3.0.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.0
  Exclude:
    - 'db/schema.rb'
    - 'bin/**'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Lint/ConstantDefinitionInBlock:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false
